### ISSUE TITLE
Update README 

### ISSUE THREAD

**Issue by samgdotson** [ansuiuc/conference-build-here#12]
The README should contain a description about the repository. This issue can be closed when the README has been updated with the correct information.

**Comment by nsryan2** [comment]
I have created a readme and code of conduct in my forked repository, I'm not certain of the process after this. The forked version I have also addresses a concern of Nate's that all of the titles saying Statement of Diversity should read Statement on Diversity.

**Comment by samgdotson** [comment]
okay, so you've made changes to the ``README`` now you should do the following:

> Go to the "Pull Requests" tab
> Select "Make a new PR"
> Select "Compare across forks" (this will allow you to compare the ansuiuc/repo to nsryan2/repo)
> Describe the PR. A good PR will address 1 or 2 issues at most (i.e. narrow in scope). 
> Ask for a reviewer to check your changes (right now this should be me). 
When you're done "Create PR".

**Comment by nsryan2** [comment]
I see that there is a readme in place. The end of the one I wrote is a code of conduct, not sure if that is useful however.

**Comment by samgdotson** [comment]
Closing this issue in deference to pull request #27
