### ISSUE TITLE
Move images to img

### ISSUE THREAD

**Issue by samgdotson** [ansuiuc/conference-build-here#25]
1. Let's be consistent with where we store images so move images from ``assets`` to ``img``. We can add a subfolder ``members`` to make organization clearer. 
2. Let's be consistent with file naming. ``lastnamefirstinitial.jpg`` is a good convention.

**Comment by nsryan2** [comment]
Ok, I updated the version of the site in my own repository. I believe that the pull request I made initially will allow you to bring these changes in, but I'm not sure exactly how they work in practice.

**Comment by samgdotson** [comment]
Closed by #26
