### ISSUE TITLE
Create page layouts for clean code. 

### ISSUE THREAD

**Issue by samgdotson** [ansuiuc/conference-build-here#47]
There is an overwhelming amount of code reused on every page that ensures navigation, footers, logos, are all there. Instead, create a ``_layouts`` folder and an ``_includes`` that will hold layouts for commonly used code such as a navigation bar, social media links, etc. This issue can be closed when
- [ ] ``_layouts`` exists in the parent directory
- [ ] ``_includes`` exists in the parent directory
- [ ] ``navbar.html`` which contains all the code for the navigation bar is placed in ``_includes``
- [ ] A default layout called ``default.html`` is in the ``_layouts`` folder. 

This will make the code much less overwhelming to read and much easier for contributors to make changes.

**Comment by nsryan2** [comment]
I found a Javascript that works pretty well, but I haven't managed to get it to work when the navbar and footer are in the _layouts/_includes folder. 

<head>
    <script src="jquery.js"></script>
    <script>
        $(function () {
            $("#DivContentnav").load("navbar.html");
        });
    </script>

    <script src="jquery.js"></script>
    <script>
        $(function () {
            $("#DivContentfooter").load("footer.html");
        });
    </script>
</head>

<body>
    <div id="DivContentnav"></div>
</body>

<p>Content goes here for each page.</p>

<body>
    <div id ="DivContentfooter"></div>
</body>

**Comment by samgdotson** [comment]
We can do all of this with ``.html``, actually!

That's why I put each of the steps needed directly in the issue. 

The top of each page file will have the following information: 

```
---
layout: default
title: page title
---
```

``default`` refers to a file in the folder ``_layouts`` called ``default.html`` which has some basic information. You can see an example [here](https://github.com/samgdotson/samgdotson.github.io/blob/master/_layouts/default.html).
The important point is that ``default.html`` has the line
```
{% include navbar.html}
```

``navbar.html`` is a file in the ``_includes`` folder that has all of the 
```
<nav>
fancy navbar stuff
</nav>
```

Does that make sense?
