### ISSUE TITLE
Add yourself to the website

### ISSUE THREAD

**Issue by nsryan2** [ansuiuc/conference-build-here#6]
<b>Request</b>
We want every member of the committee to upload their own photo, put it in the contact us webpage, add a short description of some nature (could be your level of education, major, interests) and link the photo to a professional site of theirs (whether that be linkedin or some other platform is up to you). 

<b>Expected Behavior</b>
Each Committee member should have a photo with description and link on the contact us page of the site.

<b>Actual Behavior</b>
There are currently a bunch of white hexagons on the contact us page. All of the board members are named with their title, but not all have uploaded a profile photo and completed their description and link.

<b>Steps</b>
Please upload, with the convention of your first and last name (no capitals) and underscore bars between names, to the assets folder. 

Your profile must also contain a short description of your major or interests. There's not a lot of room as the hexagons are moderately sized. As my physics teacher used to say "Brevity is the source of whit." To add your mini bio, simply type between the `<p></p>` block which should already contain your conference title. 

Updating the link your profile leads to must be done in the code for this page (contact_us.html). Search your name in the code and there will be a place that says {insert link here}, then replace the {} in the quotes with your link.

<b>Notes</b> 
I recommend that you start here as this process is set up to introduce you to a couple different functions that a lot of the site relies on. Completing this action first (if you are not familiar with html will likely be a good introduction to how this site in particular works. If you need an example, check out the contact us page to see the other board members' profiles.

<b>How can this issue be closed?</b>
When all of the board members (who are already listed with their position in the conference) have put in a photo of themselves, short description, and linked the photo to a professional site of theirs.

**Comment by samgdotson** [comment]
Closing #6 Nathan is already added.
